### ISSUE TITLE
Update Rake File

### ISSUE THREAD

**Issue by challsted** [bbourqu/cinch-yadr#8]
Need to make the rake file actually preform some form of testing
At the moment the Travis CI will just pass everytime :-1:

**Comment by bbourqu** [comment]
We'll start with linting and use [rubocop](https://github.com/bbatsov/rubocop)  After that we can start figuring out a testing framework

**Comment by challsted** [comment]
Sounds good to me :+1:

**Comment by bbourqu** [comment]
This is done for now.  Need to open a new one for code coverage.
