### ISSUE TITLE
When Returning 1 Result, don't return a breakout

### ISSUE THREAD

**Issue by challsted** [bbourqu/cinch-yadr#9]
Eg: !roll 1d6

Assuming I roll a 5

Cinch will return both "Result: 5" and "Breakout: [5]"

If i'm only rolling 1 die, I would like to not return a breakout

**Comment by bbourqu** [comment]
This also would have to work for the case of https://github.com/bbourqu/cinch-yadr/issues/10

**Comment by bbourqu** [comment]
should be easy count index on tally and if greater than one show tally

**Comment by challsted** [comment]
@bbourqu yes, this will effect Issue #10 
I have pushed a PR to you that should close that one, im working on this one now

**Comment by bbourqu** [comment]
You've got the code for this one right?

**Comment by challsted** [comment]
Its in my testing branch, i havnt tested it yet. 
If you could open a testing branch ill PR into it (or call it what ever you want, but i can only PR into your master)

**Comment by bbourqu** [comment]
https://github.com/bbourqu/cinch-yadr/tree/test

**Comment by bbourqu** [comment]
https://github.com/bbourqu/cinch-yadr/pull/13 accomplishes this
